services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
